### ISSUE TITLE
ERROR: Read_Raw_Data_Save_Into_Matlab_Files.py

### ISSUE THREAD

**Issue by chiachi926** [SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow#8]
Hello, I'm running the code "Read_Raw_Data_Save_Into_Matlab_Files.py" under the environment with python version= 2.7.18, but I always get an error shows below, is there anything wrong? Thanks!
> Traceback (most recent call last):
> File "Read_Raw_Data_Save_Into_Matlab_Files.py", line 209, in <module>
> X_105_C5, y_105_C5 = load_raw_data(electrodes=electrodes, subject=subject, num_classes=nclasses)
> File "Read_Raw_Data_Save_Into_Matlab_Files.py", line 200, in load_raw_data
> return np.array(trials, dtype=np.float64).reshape((len(trials),) + trials[0].shape + (1,)), np.array(labels, dtype=np.float64)
> IndexError: list index out of range

**Comment by imshenwei** [comment]
same error on this

**Comment by imshenwei** [comment]
same error on this

**Comment by SuperBruceJia** [comment]
> imshenwei
@chiachi926 @imshenwei 

Dear Chia-Chi and Wei, I am so sorry for the late reply! I didn't see the GitHub messages last month!

To solve this issue, first of all, please double-check your Python Environment. **Python 2.7 Environment is required.** Besides, please install ***0.1.11*** version of ***pyEDFlib***. The installation instruction is as follows:
    
```python
$ pip install pyEDFlib==0.1.11
```

Please also check my [EEG-DL](https://github.com/SuperBruceJia/EEG-DL) library for more model support and bug fixes. 

If you guys have any further questions or problems, please don't hesitate to let me know!

Best regards,

Shuyue
Nov 22, 2023

**Comment by faruqsandi** [comment]
This should not be a problem. I ran the scripts using Python 3.

For the bug mentioned in this issue, 
`IndexError: list index out of range`
the bug likely caused by the path error to electrode_positions.txt. Because of this error, `load_physionet_data` raise an exception without any warning, then return an empty list that raise an IndexError exception.

It can be fixed by replacing 
```
with io.open("electrode_positions.txt"), "r") as pos_file:
```
with
```
this_file_folder = os.path.dirname(os.path.abspath(__file__))
with io.open(os.path.join(this_file_folder, "electrode_positions.txt"), "r") as pos_file:
```

**Comment by ajaireshman267** [comment]
Dear @SuperBruceJia i have tried both your suggestion and wei suggestion but still this error persists i will mention the error below , please help me
Start to save the File!
Traceback (most recent call last):
  File "Read_Raw_Data_Save_Into_Matlab_Files.py", line 209, in <module>
    X_105_C5, y_105_C5 = load_raw_data(electrodes=electrodes, subject=subject, num_classes=nclasses)
  File "Read_Raw_Data_Save_Into_Matlab_Files.py", line 200, in load_raw_data
    return np.array(trials, dtype=np.float64).reshape((len(trials),) + trials[0].shape + (1,)), np.array(labels, dtype=np.float64)
IndexError: list index out of range
