### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ajaireshman267** [SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow#9]
Dear @SuperBruceJia i have tried both your suggestion and wei suggestion but still this error persists i will mention the error below , please help me
Start to save the File!
Traceback (most recent call last):
File "Read_Raw_Data_Save_Into_Matlab_Files.py", line 209, in
X_105_C5, y_105_C5 = load_raw_data(electrodes=electrodes, subject=subject, num_classes=nclasses)
File "Read_Raw_Data_Save_Into_Matlab_Files.py", line 200, in load_raw_data
return np.array(trials, dtype=np.float64).reshape((len(trials),) + trials[0].shape + (1,)), np.array(labels, dtype=np.float64)
IndexError: list index out of range

**Comment by rongmengmeng** [comment]
请问你解决这个问题了吗？
